/**
 * @module Interfaces.IMessageEvaluation
 *
 * This module defines interfaces for message evaluation and comparison.
 * It provides structures for comparing responses across different models,
 * calculating similarity metrics, and storing embedding information.
 */

/**
 * Interface representing a comprehensive evaluation of messages across models.
 * Contains different similarity metrics and model responses for comparison.
 */
export interface IMessageEvaluation {
  /** Messages from different models being evaluated */
  models: IModelMessage[];

  /** Cosine similarity calculations between embeddings */
  cosines: IModelCosine[];

  /** Levenshtein distance matrix between messages */
  levenshtein: number[][];

  /** Normalized Levenshtein similarity matrix (1 - distance / maxDistance) */
  levenshteinNormalized: number[][];

  /** Jaccard similarity matrix between messages */
  jaccard: number[][];
}

/**
 * Interface representing a message generated by a specific model.
 */
export interface IModelMessage {
  /** Identifier for the model that generated this message */
  modelID: string;

  /** The actual text content of the message */
  message: string;
}

/**
 * Interface representing cosine similarity calculations between embeddings.
 */
export interface IModelCosine {
  /** Information about the embedding model used */
  embeddingModel: IEmbeddingModelInfo;

  /** Matrix of cosine similarity values between embeddings */
  cosine: number[][];
}

/**
 * Interface representing embeddings generated by a specific model.
 */
export interface IModelEmbedding {
  /** Information about the embedding model used */
  embeddingModel: IEmbeddingModelInfo;

  /** 2D array of embedding vectors */
  embeddings: number[][];
}

/**
 * Interface identifying an embedding model.
 */
export interface IEmbeddingModelInfo {
  /** Identifier for the specific embedding configuration */
  embeddingID: string;

  /** Identifier for the model used to generate embeddings */
  modelID: string;
}
